---
title: "Plotly"
author: "Carolina Downie"
date: "11/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Dataset

```{r}
library(tidyverse)
library(janitor)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```


```{r}

airbnb <- read_csv("nyc_airbnb.csv") %>% clean_names() %>%
  rename(boro = neighbourhood_group) %>%
  mutate(rating = review_scores_location/2) %>%
  filter(boro == "Manhattan", room_type == "Entire home/apt", price > 100 & price < 400)
```

##Plotly Scatterplot

```{r}
airbnb %>% mutate(hover_text = str_c("Price: $", price, '\nRating:', rating)) %>%
  plot_ly(x = ~longitude, y = ~latitude, color = ~price, text = ~hover_text, 
                   type = "scatter", mode = "marker", alpha = 0.5)

#changing hover text using mutate
# \n indicates new line

```


##Plotly boxplot

```{r}
airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
           plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

```{r}
airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```


##ggplotly

```{r}
scatter_ggplot = airbnb %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
```

